# Recode Snippets

### Snippet 1: Recode many values at once

Source: [Susan Johnston's blog](http://susanejohnston.wordpress.com/2012/10/01/find-and-replace-in-r-part-2-how-to-recode-many-values-simultaneously/?utm_medium=referral&utm_source=pulsenews)  
  
Package(s) needed:
```{r}
library(car)
```
  
The function used to execute the replacement:

```{r}
recoderFunc <- function(data, oldvalue, newvalue) {

    # convert any factors to characters

    if (is.factor(data))     data     <- as.character(data)
    if (is.factor(oldvalue)) oldvalue <- as.character(oldvalue)
    if (is.factor(newvalue)) newvalue <- as.character(newvalue)

    # create the return vector

    newvec <- data

    # put recoded values into the correct position in the return vector

    for (i in unique(oldvalue)) newvec[data == i] <- newvalue[oldvalue == i]

    newvec

}
```

####Example

A vector with words to be replaced (target object is named test.words):

```{r,echo=FALSE}
test.words <- rep(c("cat", "dog", "coffee", "tea", "tee", "banter"), times = c(3, 
    5, 2, 3, 4, 2))

test.words
```

A two-column dataframe with translations (target items are under replace$English to be replaced by replace$Finnish items):

```{r, echo=FALSE}
replace <- data.frame(English = c("cat", "dog", "coffee", "tea", "tee"),
                      Finnish = c("kissa", "koira", "kahvi", "tee", "tii"))

replace
```

What it looks like:
```{r}
recoderFunc(test.words, replace$English, replace$Finnish)
```
